/**
 * SPDX-FileCopyrightText: 2026 Conduction / Dossiq Contributors
 * SPDX-License-Identifier: EUPL-1.2
 *
 * A snapshot of OpenRegister's published property vocabulary.
 *
 * The live list is served by OpenRegister at
 * `/apps/openregister/api/schemas/property-vocabulary`, generated from the
 * same tables its save-time validator reads. This file is a copy of that
 * answer, taken on 2026-09-14 from `PropertyValidatorHandler`, and it exists
 * for one case: an instance whose OpenRegister does not publish the endpoint
 * yet. The case-type editor then still has a vocabulary to render, and it
 * says out loud that it is reading a snapshot rather than the instance.
 *
 * Nothing here is dossiq's own. Every type, constraint, modifier and
 * pass-through key below is OpenRegister's, and `propertyDefinitionSchema`
 * fails the build when dossiq offers or forwards anything this file does not
 * hold. When OpenRegister widens the vocabulary, this snapshot goes stale in
 * the safe direction: it offers less than the instance accepts, never more.
 *
 * `conceptScheme` was added on 2026-09-18, when openregister#3883 published it
 * and this app began forwarding it. ONLY that key: the live vocabulary now
 * holds 99 keys against this file's 90, so the rest of the drift is left where
 * it is, in the safe direction, rather than refreshed wholesale in a change
 * that is about one binding. A snapshot is refreshed by taking it again from
 * the endpoint, not by hand, and that is its own piece of work.
 *
 * @see openspec/changes/casetype-field-vocabulary/design.md
 */

/**
 * The vocabulary as the endpoint answers it.
 *
 * @type {{types: object[], categories: string[], constraints: object[],
 *   modifiers: object[], passthrough: object[], keys: string[],
 *   vendorExtensionPrefix: string, counts: object}}
 */
export const VOCABULARY_SNAPSHOT = {
	types: [
		{
			type: 'string',
			category: 'text',
			constraints: [
				'format',
				'pattern',
				'minLength',
				'maxLength',
				'required',
				'enum',
				'const',
				'default',
				'oneOf',
				'$ref',
			],
			formats: [
				'text',
				'markdown',
				'html',
				'date-time',
				'date',
				'time',
				'duration',
				'email',
				'idn-email',
				'hostname',
				'idn-hostname',
				'ipv4',
				'ipv6',
				'uri',
				'uri-reference',
				'iri',
				'iri-reference',
				'uuid',
				'uri-template',
				'json-pointer',
				'relative-json-pointer',
				'regex',
				'url',
				'color',
				'color-hex',
				'color-hex-alpha',
				'color-rgb',
				'color-rgba',
				'color-hsl',
				'color-hsla',
				'semver',
				'bsn',
				'user',
			],
			conversion: 'supported',
			conversionNote:
				'Every stored value can be read back as text, so populated objects survive the change.',
			description: 'Text. Add a format to say which kind of text it is.',
		},
		{
			type: 'number',
			category: 'numeric',
			constraints: [
				'minimum',
				'maximum',
				'exclusiveMinimum',
				'exclusiveMaximum',
				'exclusiveMin',
				'exclusiveMax',
				'multipleOf',
				'required',
				'enum',
				'const',
				'default',
				'oneOf',
				'$ref',
			],
			formats: [],
			conversion: 'conditional',
			conversionNote:
				'A stored value that is not numeric is refused, so run a migration first.',
			description: 'A number with decimals.',
		},
		{
			type: 'integer',
			category: 'numeric',
			constraints: [
				'minimum',
				'maximum',
				'exclusiveMinimum',
				'exclusiveMaximum',
				'exclusiveMin',
				'exclusiveMax',
				'multipleOf',
				'required',
				'enum',
				'const',
				'default',
				'oneOf',
				'$ref',
			],
			formats: [],
			conversion: 'conditional',
			conversionNote:
				'A stored value that is not a whole number is refused, so run a migration first.',
			description: 'A whole number.',
		},
		{
			type: 'boolean',
			category: 'numeric',
			constraints: ['required', 'enum', 'const', 'default', 'oneOf', '$ref'],
			formats: [],
			conversion: 'conditional',
			conversionNote:
				'Only true, false and the strings that spell them convert.',
			description: 'Yes or no.',
		},
		{
			type: 'array',
			category: 'composite',
			constraints: [
				'items',
				'minItems',
				'maxItems',
				'uniqueItems',
				'required',
				'enum',
				'const',
				'default',
				'oneOf',
				'$ref',
			],
			formats: [],
			conversion: 'conditional',
			conversionNote:
				'A single stored value becomes a list of one. The other direction loses everything after the first entry.',
			description: 'A list. Use items to say what one entry looks like.',
		},
		{
			type: 'object',
			category: 'composite',
			constraints: [
				'properties',
				'required',
				'additionalProperties',
				'minProperties',
				'maxProperties',
				'enum',
				'const',
				'default',
				'oneOf',
				'$ref',
			],
			formats: [],
			conversion: 'conditional',
			conversionNote:
				'A stored value that is not an object is refused, so run a migration first.',
			description: 'A nested set of properties, stored inside this object.',
		},
		{
			type: 'null',
			category: 'composite',
			constraints: ['required', 'enum', 'const', 'default', 'oneOf', '$ref'],
			formats: [],
			conversion: 'supported',
			conversionNote: 'Nothing is stored, so there is nothing to convert.',
			description:
				'No value at all. Use it inside oneOf to allow an empty answer.',
		},
		{
			type: 'file',
			category: 'file',
			constraints: [
				'required',
				'enum',
				'const',
				'default',
				'oneOf',
				'$ref',
				'allowedTypes',
				'allowedTags',
				'autoTags',
				'maxSize',
				'fileConfiguration',
				'allowedMimeTypes',
				'uploadMaxFiles',
				'uploadMaxSizeMb',
			],
			formats: [],
			conversion: 'unsupported',
			conversionNote:
				'A file has to be uploaded. No stored value converts into one.',
			description: 'An uploaded file, stored in the object folder.',
		},
		{
			type: 'geo',
			category: 'spatial',
			constraints: ['required', 'enum', 'const', 'default', 'oneOf', '$ref'],
			formats: [],
			conversion: 'unsupported',
			conversionNote:
				'Coordinates cannot be derived from another value. Import them instead.',
			description: 'A point or a shape on the map.',
		},
		{
			type: 'color',
			category: 'presentation',
			constraints: ['required', 'enum', 'const', 'default', 'oneOf', '$ref'],
			formats: [],
			conversion: 'conditional',
			conversionNote:
				'A stored value that is not a colour is refused, so run a migration first.',
			description: 'A colour, written as hex, rgb or hsl.',
		},
		{
			type: 'recurrence',
			category: 'temporal',
			constraints: ['required', 'enum', 'const', 'default', 'oneOf', '$ref'],
			formats: [],
			conversion: 'unsupported',
			conversionNote:
				'A repeat rule cannot be derived from a date or a sentence.',
			description: 'A repeat rule, such as every second Tuesday.',
		},
		{
			type: 'NcFile',
			category: 'nextcloud',
			constraints: [
				'required',
				'enum',
				'const',
				'default',
				'oneOf',
				'$ref',
				'fileConfiguration',
				'allowedMimeTypes',
				'uploadMaxFiles',
				'uploadMaxSizeMb',
			],
			formats: [],
			conversion: 'unsupported',
			conversionNote:
				'The reference points at a file that has to exist first.',
			description: 'A link to a file already in Nextcloud.',
		},
		{
			type: 'NcMail',
			category: 'nextcloud',
			constraints: ['required', 'enum', 'const', 'default', 'oneOf', '$ref'],
			formats: [],
			conversion: 'unsupported',
			conversionNote:
				'The reference points at a message that has to exist first.',
			description: 'A link to a message in Nextcloud Mail.',
		},
		{
			type: 'NcContact',
			category: 'nextcloud',
			constraints: ['required', 'enum', 'const', 'default', 'oneOf', '$ref'],
			formats: [],
			conversion: 'unsupported',
			conversionNote:
				'The reference points at a contact that has to exist first.',
			description: 'A link to a contact in Nextcloud Contacts.',
		},
		{
			type: 'NcNote',
			category: 'nextcloud',
			constraints: ['required', 'enum', 'const', 'default', 'oneOf', '$ref'],
			formats: [],
			conversion: 'unsupported',
			conversionNote:
				'The reference points at a note that has to exist first.',
			description: 'A link to a note in Nextcloud Notes.',
		},
		{
			type: 'NcTodo',
			category: 'nextcloud',
			constraints: ['required', 'enum', 'const', 'default', 'oneOf', '$ref'],
			formats: [],
			conversion: 'unsupported',
			conversionNote:
				'The reference points at a task that has to exist first.',
			description: 'A link to a task in Nextcloud Tasks.',
		},
		{
			type: 'NcCalendarEvent',
			category: 'nextcloud',
			constraints: ['required', 'enum', 'const', 'default', 'oneOf', '$ref'],
			formats: [],
			conversion: 'unsupported',
			conversionNote:
				'The reference points at an event that has to exist first.',
			description: 'A link to an event in Nextcloud Calendar.',
		},
		{
			type: 'NcTalk',
			category: 'nextcloud',
			constraints: ['required', 'enum', 'const', 'default', 'oneOf', '$ref'],
			formats: [],
			conversion: 'unsupported',
			conversionNote:
				'The reference points at a conversation that has to exist first.',
			description: 'A link to a conversation in Nextcloud Talk.',
		},
		{
			type: 'NcDeck',
			category: 'nextcloud',
			constraints: ['required', 'enum', 'const', 'default', 'oneOf', '$ref'],
			formats: [],
			conversion: 'unsupported',
			conversionNote:
				'The reference points at a card that has to exist first.',
			description: 'A link to a card in Nextcloud Deck.',
		},
	],
	categories: [
		'text',
		'numeric',
		'composite',
		'file',
		'spatial',
		'presentation',
		'temporal',
		'nextcloud',
	],
	constraints: [
		{
			key: 'format',
			appliesTo: ['string'],
			value: 'string',
			enforced: true,
			breaking: true,
			description:
				'Which kind of text this is. Adding one to a populated property is breaking.',
		},
		{
			key: 'pattern',
			appliesTo: ['string'],
			value: 'string',
			enforced: true,
			breaking: true,
			description: 'A regular expression the value must match.',
		},
		{
			key: 'minLength',
			appliesTo: ['string'],
			value: 'integer',
			enforced: true,
			breaking: true,
			description: 'The shortest text you accept.',
		},
		{
			key: 'maxLength',
			appliesTo: ['string'],
			value: 'integer',
			enforced: true,
			breaking: true,
			description: 'The longest text you accept.',
		},
		{
			key: 'minimum',
			appliesTo: ['number', 'integer'],
			value: 'number',
			enforced: true,
			breaking: true,
			description: 'The lowest number you accept.',
		},
		{
			key: 'maximum',
			appliesTo: ['number', 'integer'],
			value: 'number',
			enforced: true,
			breaking: true,
			description: 'The highest number you accept.',
		},
		{
			key: 'exclusiveMinimum',
			appliesTo: ['number', 'integer'],
			value: 'number',
			enforced: true,
			breaking: true,
			description: 'The value must be above this number, not equal to it.',
		},
		{
			key: 'exclusiveMaximum',
			appliesTo: ['number', 'integer'],
			value: 'number',
			enforced: true,
			breaking: true,
			description: 'The value must be below this number, not equal to it.',
		},
		{
			key: 'exclusiveMin',
			appliesTo: ['number', 'integer'],
			value: 'boolean',
			enforced: true,
			breaking: true,
			description:
				'Read minimum as "above" instead of "at least". The property form writes this one.',
		},
		{
			key: 'exclusiveMax',
			appliesTo: ['number', 'integer'],
			value: 'boolean',
			enforced: true,
			breaking: true,
			description:
				'Read maximum as "below" instead of "at most". The property form writes this one.',
		},
		{
			key: 'multipleOf',
			appliesTo: ['number', 'integer'],
			value: 'number',
			enforced: true,
			breaking: true,
			description: 'The value must be a multiple of this number.',
		},
		{
			key: 'items',
			appliesTo: ['array'],
			value: 'object',
			enforced: true,
			breaking: true,
			description: 'What one entry in the list looks like.',
		},
		{
			key: 'minItems',
			appliesTo: ['array'],
			value: 'integer',
			enforced: true,
			breaking: true,
			description: 'The fewest entries you accept.',
		},
		{
			key: 'maxItems',
			appliesTo: ['array'],
			value: 'integer',
			enforced: true,
			breaking: true,
			description: 'The most entries you accept.',
		},
		{
			key: 'uniqueItems',
			appliesTo: ['array'],
			value: 'boolean',
			enforced: true,
			breaking: true,
			description: 'Refuse a list that repeats an entry.',
		},
		{
			key: 'properties',
			appliesTo: ['object'],
			value: 'object',
			enforced: true,
			breaking: true,
			description: 'The properties nested inside this one.',
		},
		{
			key: 'required',
			appliesTo: ['*'],
			value: 'boolean or array',
			enforced: true,
			breaking: true,
			description:
				'On a property, whether an answer is required. On an object, which nested properties are.',
		},
		{
			key: 'additionalProperties',
			appliesTo: ['object'],
			value: 'boolean or object',
			enforced: true,
			breaking: true,
			description: 'Whether properties you did not declare may be stored.',
		},
		{
			key: 'minProperties',
			appliesTo: ['object'],
			value: 'integer',
			enforced: true,
			breaking: true,
			description: 'The fewest nested properties you accept.',
		},
		{
			key: 'maxProperties',
			appliesTo: ['object'],
			value: 'integer',
			enforced: true,
			breaking: true,
			description: 'The most nested properties you accept.',
		},
		{
			key: 'enum',
			appliesTo: ['*'],
			value: 'array',
			enforced: true,
			breaking: true,
			description:
				'The list of answers you accept. Removing an entry refuses objects that already hold it.',
		},
		{
			key: 'const',
			appliesTo: ['*'],
			value: 'any',
			enforced: true,
			breaking: true,
			description: 'The one value you accept.',
		},
		{
			key: 'default',
			appliesTo: ['*'],
			value: 'any',
			enforced: true,
			breaking: false,
			description: 'What a new object starts with.',
		},
		{
			key: 'oneOf',
			appliesTo: ['*'],
			value: 'array',
			enforced: true,
			breaking: true,
			description: 'A list of alternative shapes. Exactly one has to match.',
		},
		{
			key: '$ref',
			appliesTo: ['*'],
			value: 'string',
			enforced: true,
			breaking: true,
			description:
				'A reference to another schema. This is how one object points at another.',
		},
		{
			key: 'allowedTypes',
			appliesTo: ['file'],
			value: 'array',
			enforced: true,
			breaking: false,
			description: 'The MIME types you accept on upload.',
		},
		{
			key: 'allowedTags',
			appliesTo: ['file'],
			value: 'array',
			enforced: true,
			breaking: false,
			description: 'The tags a person may put on the upload.',
		},
		{
			key: 'autoTags',
			appliesTo: ['file'],
			value: 'array',
			enforced: true,
			breaking: false,
			description: 'The tags every upload gets automatically.',
		},
		{
			key: 'maxSize',
			appliesTo: ['file'],
			value: 'integer',
			enforced: true,
			breaking: false,
			description: 'The largest upload you accept, in bytes, up to 100 MB.',
		},
		{
			key: 'fileConfiguration',
			appliesTo: ['file', 'NcFile'],
			value: 'object',
			enforced: true,
			breaking: false,
			description: 'Where the upload lands and how many files fit.',
		},
		{
			key: 'allowedMimeTypes',
			appliesTo: ['file', 'NcFile'],
			value: 'array',
			enforced: true,
			breaking: false,
			description: 'The MIME types the upload field offers.',
		},
		{
			key: 'uploadMaxFiles',
			appliesTo: ['file', 'NcFile'],
			value: 'integer',
			enforced: true,
			breaking: false,
			description: 'How many files one answer may hold.',
		},
		{
			key: 'uploadMaxSizeMb',
			appliesTo: ['file', 'NcFile'],
			value: 'integer',
			enforced: true,
			breaking: false,
			description: 'The largest upload you accept, in megabytes.',
		},
	],
	modifiers: [
		{
			key: 'title',
			value: 'string',
			enforced: true,
			description: 'The label a person reads above the field.',
		},
		{
			key: 'description',
			value: 'string',
			enforced: true,
			description: 'The sentence under the field.',
		},
		{
			key: 'example',
			value: 'any',
			enforced: true,
			description: 'A sample answer, shown in the API documentation.',
		},
		{
			key: 'order',
			value: 'number',
			enforced: true,
			description: 'Where the field sits in the form.',
		},
		{
			key: 'behavior',
			value: 'string',
			enforced: true,
			description: 'How the field behaves in the form.',
		},
		{
			key: 'visible',
			value: 'boolean',
			enforced: true,
			description:
				'Set this to false and the property disappears from every read.',
		},
		{
			key: 'hideOnCollection',
			value: 'boolean',
			enforced: true,
			description: 'Keep the field out of the list view.',
		},
		{
			key: 'hideOnForm',
			value: 'boolean',
			enforced: true,
			description: 'Keep the field out of the form.',
		},
		{
			key: 'readOnly',
			value: 'boolean',
			enforced: true,
			description: 'Show the value, refuse a write.',
		},
		{
			key: 'writeOnly',
			value: 'boolean',
			enforced: true,
			description: 'Accept a write, never read it back.',
		},
		{
			key: 'immutable',
			value: 'boolean',
			enforced: true,
			description: 'Accept the first answer, refuse every change after it.',
		},
		{
			key: 'deprecated',
			value: 'boolean',
			enforced: true,
			description: 'Mark the field as on its way out.',
		},
		{
			key: 'facetable',
			value: 'boolean',
			enforced: true,
			description: 'Offer the field as a filter in search.',
		},
		{
			key: 'facetConfig',
			value: 'object',
			enforced: true,
			description: 'How the filter buckets its values.',
		},
		{
			key: 'aggregated',
			value: 'boolean',
			enforced: true,
			description: 'Count the field in aggregations.',
		},
		{
			key: 'translatable',
			value: 'boolean',
			enforced: true,
			description: 'Store one value per language.',
		},
		{
			key: 'sourceLanguage',
			value: 'string',
			enforced: true,
			description:
				'Which language the authored value is in. Needs translatable.',
		},
		{
			key: 'calculation',
			value: 'object',
			enforced: true,
			description:
				'Derive the value from other properties instead of asking for it.',
		},
		{
			key: 'computed',
			value: 'string',
			enforced: true,
			description: 'A Twig expression that derives the value.',
		},
		{
			key: 'onDelete',
			value: 'string',
			enforced: true,
			description:
				'What happens to this object when the one it points at is deleted.',
		},
		{
			key: 'cascade',
			value: 'boolean',
			enforced: true,
			description: 'Save the referenced object along with this one.',
		},
		{
			key: 'cascadeDelete',
			value: 'boolean',
			enforced: true,
			description: 'Delete the referenced object along with this one.',
		},
		{
			key: 'inversedBy',
			value: 'string',
			enforced: true,
			description: 'The property on the other side of the relation.',
		},
		{
			key: 'register',
			value: 'string',
			enforced: true,
			description: 'The register the referenced object lives in.',
		},
		{
			key: 'schema',
			value: 'string',
			enforced: true,
			description: 'The schema the referenced object follows.',
		},
		{
			key: 'writeBack',
			value: 'boolean',
			enforced: true,
			description: 'Write changes back to the referenced object.',
		},
		{
			key: 'removeAfterWriteBack',
			value: 'boolean',
			enforced: true,
			description: 'Drop the nested copy once it is written back.',
		},
		{
			key: 'objectConfiguration',
			value: 'object',
			enforced: true,
			description: 'Whether a reference is stored nested, by id or by URL.',
		},
		{
			key: 'validateReference',
			value: 'boolean',
			enforced: true,
			description: 'Check that the referenced object exists before saving.',
		},
		{
			key: 'validationStrictness',
			value: 'string',
			enforced: true,
			description: 'How hard a failed check refuses the write.',
		},
		{
			key: 'referenceType',
			value: 'string',
			enforced: true,
			description: 'What kind of thing the reference points at.',
		},
		{
			key: 'referenceSemanticType',
			value: 'string',
			enforced: true,
			description: 'The semantic type the reference resolves to.',
		},
		{
			key: 'referenceSemanticApp',
			value: 'string',
			enforced: true,
			description: 'The app that owns the semantic type.',
		},
		{
			key: 'iri',
			value: 'string',
			enforced: true,
			description: 'The vocabulary term this property means.',
		},
		{
			key: 'domains',
			value: 'array',
			enforced: true,
			description: 'The classes this property may be used on.',
		},
		{
			key: 'ranges',
			value: 'array',
			enforced: true,
			description: 'The classes this property may point at.',
		},
		{
			key: 'conceptScheme',
			value: 'string',
			enforced: true,
			description: 'The SKOS concept scheme this field takes its choices from, by slug.',
		},
	],
	passthrough: [
		{
			key: '$id',
			enforced: false,
			description: 'The identifier of this sub-schema.',
		},
		{
			key: '$schema',
			enforced: false,
			description: 'Which JSON Schema draft the author wrote against.',
		},
		{
			key: '$comment',
			enforced: false,
			description: 'A note for whoever reads the schema next.',
		},
		{
			key: 'comment',
			enforced: false,
			description: 'A note for whoever reads the schema next.',
		},
		{
			key: 'examples',
			enforced: false,
			description: 'Sample answers, shown in the API documentation.',
		},
		{
			key: 'nullable',
			enforced: false,
			description: 'The OpenAPI 3.0 spelling of "an empty answer is allowed".',
		},
		{
			key: 'allOf',
			enforced: false,
			description:
				'Every listed shape has to match. Stored, not enforced here.',
		},
		{
			key: 'anyOf',
			enforced: false,
			description:
				'At least one listed shape has to match. Stored, not enforced here.',
		},
		{
			key: 'not',
			enforced: false,
			description:
				'The listed shape must not match. Stored, not enforced here.',
		},
		{
			key: 'if',
			enforced: false,
			description: 'The condition of a conditional sub-schema.',
		},
		{
			key: 'then',
			enforced: false,
			description: 'The shape that applies when the condition matches.',
		},
		{
			key: 'else',
			enforced: false,
			description: 'The shape that applies when the condition does not match.',
		},
		{
			key: 'contains',
			enforced: false,
			description: 'At least one list entry has to match this shape.',
		},
		{
			key: 'prefixItems',
			enforced: false,
			description: 'The shape of the first entries of a list, in order.',
		},
		{
			key: 'patternProperties',
			enforced: false,
			description:
				'Nested properties matched by name against a regular expression.',
		},
		{
			key: 'propertyNames',
			enforced: false,
			description: 'A shape every nested property name has to match.',
		},
		{
			key: 'dependentRequired',
			enforced: false,
			description:
				'Which properties become required once this one is answered.',
		},
		{
			key: 'contentMediaType',
			enforced: false,
			description: 'The media type of the encoded content.',
		},
		{
			key: 'contentEncoding',
			enforced: false,
			description: 'How the content is encoded.',
		},
	],
	keys: [
		'type',
		'format',
		'pattern',
		'minLength',
		'maxLength',
		'minimum',
		'maximum',
		'exclusiveMinimum',
		'exclusiveMaximum',
		'exclusiveMin',
		'exclusiveMax',
		'multipleOf',
		'items',
		'minItems',
		'maxItems',
		'uniqueItems',
		'properties',
		'required',
		'additionalProperties',
		'minProperties',
		'maxProperties',
		'enum',
		'const',
		'default',
		'oneOf',
		'$ref',
		'allowedTypes',
		'allowedTags',
		'autoTags',
		'maxSize',
		'fileConfiguration',
		'allowedMimeTypes',
		'uploadMaxFiles',
		'uploadMaxSizeMb',
		'title',
		'description',
		'example',
		'order',
		'behavior',
		'visible',
		'hideOnCollection',
		'hideOnForm',
		'readOnly',
		'writeOnly',
		'immutable',
		'deprecated',
		'facetable',
		'facetConfig',
		'aggregated',
		'translatable',
		'sourceLanguage',
		'calculation',
		'computed',
		'onDelete',
		'cascade',
		'cascadeDelete',
		'inversedBy',
		'register',
		'schema',
		'writeBack',
		'removeAfterWriteBack',
		'objectConfiguration',
		'validateReference',
		'validationStrictness',
		'referenceType',
		'referenceSemanticType',
		'referenceSemanticApp',
		'iri',
		'domains',
		'ranges',
		'$id',
		'$schema',
		'$comment',
		'comment',
		'examples',
		'nullable',
		'allOf',
		'anyOf',
		'not',
		'if',
		'then',
		'else',
		'contains',
		'prefixItems',
		'patternProperties',
		'propertyNames',
		'dependentRequired',
		'contentMediaType',
		'contentEncoding',
		'conceptScheme',
	],
	vendorExtensionPrefix: 'x-',
	counts: {
		types: 19,
		constraints: 33,
		modifiers: 37,
		passthrough: 19,
		formats: 33,
		keys: 90,
	},
}
