<?php

/**
 * Guards the `case` schema declarations the case-identity change rests on.
 *
 * @category Tests
 * @package  OCA\Dossiq\Tests\Unit\Settings
 *
 * @author    Conduction Development Team <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * @version GIT: <git-id>
 *
 * @link https://conduction.nl
 *
 * SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
 * SPDX-License-Identifier: EUPL-1.2
 */

declare(strict_types=1);

namespace OCA\Dossiq\Tests\Unit\Settings;

use PHPUnit\Framework\TestCase;

/**
 * A case number nobody types, read straight off the shipped register.
 *
 * The declaration is the whole feature: `identifier` is generated by
 * OpenRegister's `sequence` operator, so nothing in dossiq's own code says
 * what the number looks like. A test that rebuilt the expression from a
 * fixture would therefore assert nothing at all — it reads
 * `lib/Settings/dossiq_register.json`, the file that actually ships.
 *
 * @spec openspec/specs/case-management/spec.md
 */
class CaseIdentitySchemaTest extends TestCase {

	/**
	 * The `case` schema as shipped.
	 *
	 * @var array<string, mixed>
	 */
	private array $caseSchema = [];

	/**
	 * The `complaint` schema as shipped.
	 *
	 * @var array<string, mixed>
	 */
	private array $complaintSchema = [];

	/**
	 * Load the shipped register once per test.
	 *
	 * @return void
	 */
	protected function setUp(): void {
		parent::setUp();

		$path = __DIR__ . '/../../../lib/Settings/dossiq_register.json';
		$raw = file_get_contents($path);
		$this->assertIsString($raw, 'the shipped register must be readable');

		$register = json_decode($raw, true);
		$this->assertIsArray($register, 'the shipped register must be valid JSON');

		$this->caseSchema      = $register['components']['schemas']['case'];
		$this->complaintSchema = $register['components']['schemas']['complaint'];
	}//end setUp()

	/**
	 * The case number is declared, issued by the platform and never typed.
	 *
	 * `x-openregister-generated` replaced the `x-openregister-calculations`
	 * expression this file used to assert (openregister#3785). The difference is
	 * not cosmetic: the annotation takes the number under a lock inside the
	 * create transaction, where the calculation's `sequence` operator did not, so
	 * two cases filed in the same second can no longer be handed one number.
	 *
	 * @return void
	 */
	public function testIdentifierIsIssuedFromANamedYearlySequence(): void {
		$identifier = $this->caseSchema['properties']['identifier'];

		$this->assertTrue(
			$identifier['readOnly'],
			'a generated number must be read-only on every form'
		);
		$this->assertArrayNotHasKey(
			'format',
			$identifier,
			'adding a format to an existing property is breaking in OpenRegister'
		);

		$this->assertSame(
			[
				'sequence' => 'case',
				'format'   => '{year}-{seq:4}',
				'resetOn'  => 'year',
			],
			$identifier['x-openregister-generated'],
			'the case number is the filing year, a hyphen and a four-digit counter that restarts each year'
		);
	}//end testIdentifierIsIssuedFromANamedYearlySequence()

	/**
	 * Exactly one mechanism writes the number.
	 *
	 * The calculation entry and the annotation are both writers on the create
	 * path, each correct on its own and neither able to see what the other did.
	 * Whichever ran first would win, and the counter would then be advanced by
	 * the loser: a number spent on nothing, every case, for ever.
	 *
	 * This is the assertion that makes the removal permanent. Re-adding the
	 * calculation entry to a 10,500-line file is a one-line edit nobody would
	 * notice in review.
	 *
	 * @return void
	 */
	public function testNoCalculationWritesTheIdentifier(): void {
		$calculations = $this->caseSchema['configuration']['x-openregister-calculations'];

		$this->assertArrayNotHasKey(
			'identifier',
			$calculations,
			'two writers on one field is how a counter is spent on a number nobody sees'
		);
		$this->assertNotSame(
			[],
			$calculations,
			'a control: the calculations block still holds the other entries, so the absence above means something'
		);
	}//end testNoCalculationWritesTheIdentifier()

	/**
	 * The pad the format declares is the pad the seeded cases carry.
	 *
	 * A widened pad would leave one install holding both shapes, and OpenRegister
	 * cannot renumber an identifier it already issued (REQ-GID-006, unshipped).
	 * So the two have to be checked against each other rather than each against a
	 * number typed into a test.
	 *
	 * @return void
	 */
	public function testTheSeededNumbersMatchTheDeclaredFormat(): void {
		$format = $this->caseSchema['properties']['identifier']['x-openregister-generated']['format'];

		$this->assertSame(
			1,
			preg_match('/^\\{year\\}-\\{seq:(\\d+)\\}$/', $format, $found),
			'the format is the year, a hyphen and a padded counter'
		);
		$pad = (int)$found[1];

		$path = __DIR__ . '/../../../lib/Settings/register.d/46-demo-cases-english.json';
		$raw  = file_get_contents($path);
		$this->assertIsString($raw, 'the shipped demo cases must be readable');

		$fragment = json_decode($raw, true);
		$this->assertIsArray($fragment, 'the shipped demo fragment must be valid JSON');

		// Only the CASE objects. A `caseType` carries an `identifier` too, and it
		// is a slug: a text scan of the file reads `building-permit` as a case
		// number and the assertion then says nothing about either.
		$seeded = [];
		foreach (($fragment['components']['objects'] ?? []) as $object) {
			if (($object['@self']['schema'] ?? '') !== 'case') {
				continue;
			}

			if (isset($object['identifier']) === true) {
				$seeded[] = (string)$object['identifier'];
			}
		}

		$this->assertNotEmpty($seeded, 'a control: the demo file must actually carry case numbers');
		foreach ($seeded as $value) {
			$this->assertSame(
				1,
				preg_match('/^\\d{4}-\\d{' . $pad . ',}$/', $value),
				$value . ' does not read as the format the schema declares'
			);
		}
	}//end testTheSeededNumbersMatchTheDeclaredFormat()

	/**
	 * Tags are free words, and the index can filter on them.
	 *
	 * `facetable: true` is the load-bearing half. `filtersFromSchema` builds the
	 * index sidebar from exactly that key, so without it the property exists,
	 * the sidebar tab renders, and the Cases index offers no Tags filter at all
	 * — a half-feature that looks finished from the case page.
	 *
	 * @return void
	 */
	public function testTagsAreFreeWordsTheIndexCanFilterOn(): void {
		$tags = $this->caseSchema['properties']['tags'];

		$this->assertSame('array', $tags['type']);
		$this->assertSame('string', $tags['items']['type']);
		$this->assertTrue($tags['facetable'], 'the Cases index filter is built from facetable');
	}//end testTagsAreFreeWordsTheIndexCanFilterOn()

	/**
	 * The statutory fields are readable, which is not the same as declared.
	 *
	 * All five archive and payment properties were declared AND carried
	 * `visible: false`, which drops a property from every schema-driven surface
	 * at once — data widget, form dialog, index filters. The change is
	 * therefore not "add a widget over existing fields": without this, the
	 * widget renders an empty grid and the manifest still looks right.
	 *
	 * @return void
	 */
	public function testTheStatutoryFieldsAreVisible(): void {
		$statutory = [
			'legalBasis',
			'statutoryTerm',
			'archiveNomination',
			'archiveActionDate',
			'archiveStatus',
			'paymentIndication',
			'lastPaymentDate',
		];

		foreach ($statutory as $key) {
			$property = $this->caseSchema['properties'][$key];
			$this->assertArrayNotHasKey(
				'visible',
				$property,
				$key . ' renders on no surface at all while it carries visible: false'
			);
			$this->assertNotSame(
				'',
				trim((string)($property['title'] ?? '')),
				$key . ' needs a label a person can read'
			);
		}
	}//end testTheStatutoryFieldsAreVisible()

	/**
	 * The statutory lead time is copied onto the case, not read through a path.
	 *
	 * The design asked for `extend: ["caseType"]` plus the include path
	 * `caseType.processingDeadline`. A data widget builds its fields from
	 * `Object.entries(schema.properties)`, so a dotted include matches no
	 * property and the row simply never appears — the escape hatch task 3.2
	 * names. Copying the type's duration onto the case with the same `@ref`
	 * mechanism `deadline` already uses puts a real property behind the row.
	 *
	 * @return void
	 */
	public function testTheStatutoryLeadTimeIsCopiedFromTheCaseType(): void {
		$calculation = $this->caseSchema['configuration']['x-openregister-calculations']['statutoryTerm'];

		$this->assertTrue($calculation['materialise'], 'a cross-object @ref resolves at save time only');
		$this->assertSame(
			['prop' => '@ref.caseType.processingDeadline'],
			$calculation['expression']
		);
	}//end testTheStatutoryLeadTimeIsCopiedFromTheCaseType()

	/**
	 * The schema version moves whenever the schema does.
	 *
	 * OpenRegister fast-skips a schema whose version has not changed, so a new
	 * property on an unchanged version lands on a fresh install and on nothing
	 * else. The assertion is deliberately "past 1.14.0", the version this
	 * change found: pinning the exact number would turn every later edit into a
	 * failing test that says nothing about correctness.
	 *
	 * @return void
	 */
	/**
	 * The klachtnummer comes from its own counter, not from a count of rows.
	 *
	 * `ComplaintService::generateComplaintNumber` searched this year's
	 * complaints and returned COUNT + 1. Delete one complaint and the next one
	 * filed is handed a number a live complaint already holds. Nothing in the
	 * service could see that, because the collision is in the register.
	 *
	 * The counter is the complaint's own rather than the case counter, so a
	 * citizen holding two letters cannot read off how many cases were filed
	 * between them.
	 *
	 * @return void
	 */
	public function testTheComplaintNumberIsIssuedFromItsOwnCounter(): void {
		$number = $this->complaintSchema['properties']['complaintNumber'];

		$this->assertTrue($number['readOnly'], 'a generated number must be read-only on every form');
		$this->assertSame(
			[
				'sequence' => 'complaint',
				'format'   => 'KL-{year}-{seq:4}',
				'resetOn'  => 'year',
			],
			$number['x-openregister-generated']
		);

		$caseSequence = $this->caseSchema['properties']['identifier']['x-openregister-generated']['sequence'];
		$this->assertNotSame(
			$caseSequence,
			$number['x-openregister-generated']['sequence'],
			'two schemas naming one sequence draw from one counter, which is not what a klachtnummer wants'
		);
	}//end testTheComplaintNumberIsIssuedFromItsOwnCounter()

	/**
	 * The complaint schema version moved with the annotation.
	 *
	 * OpenRegister fast-skips a schema whose version has not changed, so the
	 * annotation would land on a fresh install and on nothing else.
	 *
	 * @return void
	 */
	public function testTheComplaintSchemaVersionMoved(): void {
		$this->assertGreaterThan(
			0,
			version_compare($this->complaintSchema['version'], '1.0.0'),
			'an annotation on an unbumped version never reaches an existing install'
		);
	}//end testTheComplaintSchemaVersionMoved()

	public function testTheSchemaVersionMovedWithTheSchema(): void {
		$this->assertGreaterThan(
			0,
			version_compare($this->caseSchema['version'], '1.14.0'),
			'a new property on an unbumped version never reaches an existing install'
		);
	}//end testTheSchemaVersionMovedWithTheSchema()
}//end class
