<?php

/**
 * Guards the `case` schema declarations the case-identity change rests on.
 *
 * @category Tests
 * @package  OCA\Dossiq\Tests\Unit\Settings
 *
 * @author    Conduction Development Team <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * @version GIT: <git-id>
 *
 * @link https://conduction.nl
 *
 * SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
 * SPDX-License-Identifier: EUPL-1.2
 */

declare(strict_types=1);

namespace OCA\Dossiq\Tests\Unit\Settings;

use PHPUnit\Framework\TestCase;

/**
 * A case number nobody types, read straight off the shipped register.
 *
 * The declaration is the whole feature: `identifier` is generated by
 * OpenRegister's `sequence` operator, so nothing in dossiq's own code says
 * what the number looks like. A test that rebuilt the expression from a
 * fixture would therefore assert nothing at all — it reads
 * `lib/Settings/dossiq_register.json`, the file that actually ships.
 *
 * @spec openspec/specs/case-management/spec.md
 */
class CaseIdentitySchemaTest extends TestCase {

	/**
	 * The `case` schema as shipped.
	 *
	 * @var array<string, mixed>
	 */
	private array $caseSchema = [];

	/**
	 * Load the shipped register once per test.
	 *
	 * @return void
	 */
	protected function setUp(): void {
		parent::setUp();

		$path = __DIR__ . '/../../../lib/Settings/dossiq_register.json';
		$raw = file_get_contents($path);
		$this->assertIsString($raw, 'the shipped register must be readable');

		$register = json_decode($raw, true);
		$this->assertIsArray($register, 'the shipped register must be valid JSON');

		$this->caseSchema = $register['components']['schemas']['case'];
	}//end setUp()

	/**
	 * The case number is declared, generated and never typed.
	 *
	 * @return void
	 */
	public function testIdentifierIsAGeneratedYearlySequence(): void {
		$identifier = $this->caseSchema['properties']['identifier'];

		$this->assertTrue(
			$identifier['readOnly'],
			'a generated number must be read-only on every form'
		);
		$this->assertArrayNotHasKey(
			'format',
			$identifier,
			'adding a format to an existing property is breaking in OpenRegister'
		);

		$calculation = $this->caseSchema['configuration']['x-openregister-calculations']['identifier'];

		$this->assertTrue($calculation['materialise'], 'the number is stored, not recomputed per read');
		$this->assertSame(
			[
				'concat' => [
					['year' => ['prop' => 'startDate']],
					'-',
					['sequence' => ['scope' => 'yearly', 'pad' => 4]],
				],
			],
			$calculation['expression'],
			'the number is the start year, a hyphen and a four-digit yearly sequence'
		);
	}//end testIdentifierIsAGeneratedYearlySequence()
}//end class
