<?php

/**
 * Test stub for OpenRegister's ObjectEntity.
 *
 * Minimal surface needed by dossiq unit tests: the audit listener resolves an
 * ObjectEntity from OR's ObjectService and hands it to AuditTrailMapper. Only
 * the accessors the dossiq code touches are stubbed.
 *
 * @category Stub
 * @package  OCA\OpenRegister\Db
 *
 * @author    Conduction Development Team <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EUPL-1.2
 * SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
 *
 * @link https://conduction.nl
 */

declare(strict_types=1);

namespace OCA\OpenRegister\Db;

/**
 * Stub of OpenRegister's ObjectEntity for unit tests.
 */
class ObjectEntity implements \OCA\OpenRegister\Contract\ObjectEntityInterface {
	/**
	 * @return ?string
	 */
	public function getRegister(): ?string {
		return $this->register ?? null;
	}

	/**
	 * @return ?string
	 */
	public function getSchema(): ?string {
		return $this->schema ?? null;
	}

	/**
	 * @return ?string
	 */
	public function getOrganisation(): ?string {
		return $this->organisation ?? null;
	}

	/**
	 * @return ?string
	 */
	public function getOwner(): ?string {
		return $this->owner ?? null;
	}

	/**
	 * Object UUID.
	 *
	 * @var string|null
	 */
	private ?string $uuid = null;

	/**
	 * Raw object data (excl. `@self`).
	 *
	 * @var array<string, mixed>
	 */
	private array $object = [];

	/**
	 * Schema identifier surfaced under `@self.schema` by jsonSerialize().
	 *
	 * Named `schema`, as the real entity's column is. The name is load-bearing
	 * on the real class, where the accessors are generated by
	 * `OCP\AppFramework\Db\Entity::__call` over the DECLARED properties, so a
	 * property the real class does not declare is a setter that does not exist.
	 *
	 * @var string|null
	 */
	private ?string $schema = null;

	/**
	 * Deletion metadata surfaced under `@self.deleted` by jsonSerialize().
	 *
	 * ⚠️ Defaults to `[]`, NOT `null`, exactly as the real entity does. A live
	 * row never has `setDeleted()` called on it and keeps this default, so
	 * `getDeleted() === null` is false for every object that has ever existed
	 * and a guard written that way does not guard. The real class says the
	 * same in its own docblock; the stub repeats it because a stub that is
	 * kinder than the real thing hides the bug rather than reproducing it.
	 *
	 * @var array<string, mixed>|null
	 */
	private ?array $deleted = [];

	/**
	 * Set the deletion metadata, as `DeleteObject` does before it saves a
	 * soft delete.
	 *
	 * @param array<string, mixed>|null $deleted Deletion details.
	 *
	 * @return void
	 */
	public function setDeleted(?array $deleted): void {
		$this->deleted = $deleted;
	}//end setDeleted()

	/**
	 * Get the deletion metadata.
	 *
	 * @return array<string, mixed>|null
	 */
	public function getDeleted(): ?array {
		return $this->deleted;
	}//end getDeleted()

	/**
	 * Get the object UUID.
	 *
	 * @return string|null
	 */
	public function getUuid(): ?string {
		return $this->uuid;
	}//end getUuid()

	/**
	 * Set the object UUID.
	 *
	 * @param string|null $uuid The UUID
	 *
	 * @return void
	 */
	public function setUuid(?string $uuid): void {
		$this->uuid = $uuid;
	}//end setUuid()

	/**
	 * Set the raw object data.
	 *
	 * @param array<string, mixed> $object Object data
	 *
	 * @return void
	 */
	public function setObject(array $object): void {
		$this->object = $object;
	}//end setObject()

	/**
	 * Get the object data (excl. `@self`), with the uuid as `id` in front.
	 *
	 * The real `ObjectEntity::getObject()` does
	 * `array_merge(['id' => $this->uuid], $this->object ?? [])`. This stub used
	 * to return the raw data alone, so a caller that reads a `findAll()` row
	 * through `getObject()` and writes it back by its `id` (tenant quotas do)
	 * saw no `id` under test and would have created a new row instead of
	 * updating the one it read, while the real class never did.
	 *
	 * @return array<string, mixed>
	 */
	public function getObject(): array {
		return array_merge(['id' => $this->uuid], $this->object);
	}//end getObject()

	/**
	 * Set the schema identifier surfaced under `@self.schema`.
	 *
	 * 🔴 `setSchemaId()` USED TO SIT BESIDE THIS, AND IS GONE.
	 *
	 * The real ObjectEntity declares no `schemaId` property, so it serves no
	 * `setSchemaId()`: the call raises
	 * `BadFunctionCallException: schemaId is not a valid attribute`. The stub
	 * offered it anyway, and 23 assertions across three listener suites were
	 * written against a method that exists nowhere but here. Nothing in `lib/`
	 * called it — checked, twice, and the drift check now keeps checking —
	 * but that was luck, not design, and it is exactly how a stub-only method
	 * reaches production code.
	 *
	 * @param string|null $schema Schema identifier.
	 *
	 * @return void
	 */
	public function setSchema(?string $schema): void {
		$this->schema = $schema;
	}//end setSchema()

	/**
	 * Retention metadata, as the real entity's `retention` json column holds it.
	 *
	 * @var array<string, mixed>|null
	 */
	private ?array $retention = [];

	/**
	 * Set the retention metadata.
	 *
	 * @param array<string, mixed>|null $retention Retention details.
	 *
	 * @return void
	 */
	public function setRetention(?array $retention): void {
		$this->retention = $retention;
	}//end setRetention()

	/**
	 * Get the retention metadata.
	 *
	 * @return array<string, mixed>|null
	 */
	public function getRetention(): ?array {
		return $this->retention;
	}//end getRetention()

	/**
	 * Whether an active legal hold keeps this record from being destroyed.
	 *
	 * Mirrors the real `ObjectEntity::hasActiveLegalHold()` line for line: it
	 * is OpenRegister's SINGLE definition of held, and a stub that answered it
	 * differently would let a guard pass here and refuse in production. A
	 * RELEASED hold leaves the `legalHold` key in place with `active: false`,
	 * so the presence of the key is not the question.
	 *
	 * @return bool True when the record carries an active legal hold.
	 */
	public function hasActiveLegalHold(): bool {
		$retention = ($this->getRetention() ?? []);

		return ((($retention['legalHold'] ?? [])['active'] ?? false) === true);
	}//end hasActiveLegalHold()

	/**
	 * Minimal stand-in for the real ObjectEntity::jsonSerialize() — merges
	 * the raw object data with an `@self.schema` (and `@self.id`) envelope,
	 * matching the fields dossiq listeners actually read.
	 *
	 * @return array<string, mixed>
	 */
	public function jsonSerialize(): array {
		$data = $this->object;
		$data['@self'] = [
			'schema' => $this->schema,
			'id' => $this->uuid,
			// The real getObjectArray() puts the retention column in `@self`,
			// which is where a reader without the entity in hand finds it.
			'retention' => $this->retention,
			'deleted' => $this->deleted,
		];

		// 🔴 TOP-LEVEL id, because the real class guarantees one.
		//
		// OCA\OpenRegister\Db\ObjectEntity::jsonSerialize() sets
		// `$object['id'] = $this->uuid` under a comment reading "Ensure id is
		// always accessible at top level (not just in @self)". This stub put
		// it only in @self, so VergunningaanvraagCreatedListener — which reads
		// `$object['id']`, correctly — found none and returned early.
		//
		// The test that would have caught it was SKIPPING, because
		// ObjectCreatedEvent had no stub and `class_exists()` said so. A skip
		// cannot tell "not applicable" from "broken".
		if ($this->uuid !== null && isset($data['id']) === false) {
			$data['id'] = $this->uuid;
		}

		return $data;
	}//end jsonSerialize()
}//end class
